### ISSUE TITLE
Application crash on creating a new dimension table

### ISSUE THREAD

**Issue by PDumasBAR** [zazuko/data-cube-curation#228] opened 2020-02-17 16:11 UTC
## Current behavior
The application has crashed, while creating a new dimension table in the project :
https://datacube.zazukoians.org/app/projects/https:%2F%2Fdatacube.zazukoians.org%2Fproject%2Fc9a4ea49-2fdb-44d0-b6bd-9fd33d68a631/sources 

I have to kill and restart the browser.
Now, when I open the project there is a red pop up in the lower right corner, but no message inside, just an exclamation point icon.

Each time I try to create a dimension table from the same CSV (DimEinteilungArt.csv), the application crash again, mainly when typing the table name or filling the template id.

Carfully (avoiding any mistyping) I can fill these 2 fields and save the new dimension table.
The red pop up is still present.

**Comment by PDumasBAR** [comment] 2020-02-27 16:49
Perhaps a start of solution for this bug. Today with Jean-Luc we tried to create a new dimension table and the application crashed 3 times in the form, when entering the name of the table, at 14 characters. There seems to be a limit for this field. A shorter name works fine.

**Comment by martinmaillard** [comment] 2020-03-02 12:26
I was not able to reproduce this issue. Is it still happening? What do you mean by "the application crashed"?

**Comment by PDumasBAR** [comment] 2020-03-02 13:00
It seems the issue is corrected. I can now create a table with a name longer than 14 characters without crashing the application. By "crash", I mean, I have to kill all the browser instances (Firefox) and restart.

**Comment by PDumasBAR** [comment] 2020-03-02 13:08
Sorry. I second test results in the same behaviour. It seems not only the length of the name is involved in the problem. If you type the start of name, wait a little and continue typing, the application as some problem (no more crash). If the formular as enough time to populate the actual name to the Identifier Attribute Template, it becomes very diffcult to continue to fill the name.

**Comment by martinmaillard** [comment] 2020-03-02 13:11
Ok thank you. I will test with Firefox to see if it also happens for me.

**Comment by PDumasBAR** [comment] 2020-03-02 13:45
Here a screenshot from the StapferNew project when I try to create a dimension table with the DimEinteilungArt.csv.
If I wait a little while typing the name (after 13 characters), the application stops responding.

![image](https://user-images.githubusercontent.com/35593772/75681407-d0b9b200-5c93-11ea-9420-dc656efbce6d.png)

**Comment by martinmaillard** [comment] 2020-03-02 16:16
I found the cause of the issue. I didn't see it before because it was specific to Firefox. It will be fixed today.

**Comment by PDumasBAR** [comment] 2020-03-02 16:18
Thanks

**Closed** 2020-03-02 16:50 UTC
Labels: bug
