### ISSUE TITLE
Erreur dans view-mapping - projet SR1-fin, table Facts-categorie

### ISSUE THREAD

**Issue by cochardjl** [zazuko/data-cube-curation#208] opened 2020-02-04 10:09 UTC
J'ai réussi à établir un mapping entre la tables facts et la table Dim1.
La fenêtre de définition du mapping n'est pas encore très claire à mon avis mais je crois avoir configuré correctement la liaison.
View mapping et Preview mapped data donnent un message d'erreur.

=> améliorer le message d'erreur s'il est justifié
=> améliorer la fenêtre d'établissement du mapping

**Comment by martinmaillard** [comment] 2020-02-04 15:36
Probably a duplicate of #203. Should be fixed later today.

**Comment by cochardjl** [comment] 2020-02-05 12:34
It works now by me. Was the problem fixed on your side or was it a problem by me?

**Comment by martinmaillard** [comment] 2020-02-05 12:37
It was a bug that was fixed on our side yesterday.

Since you mentioned that the dialog to link tables together was not clear, could you please elaborate on what was confusing for you? We tried to improve it already, but the concept is not easy to explain and having external feedback would be very helpful!

**Closed** 2020-03-02 09:31 UTC
